In [ ]:
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.utils import to_categorical
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

df = pd.read_csv("/content/HR_DataSet.csv")

In [ ]:
df.head()

satisfaction_level  last_evaluation  number_project  average_montly_hours  \
0                0.38             0.53               2                   157   
1                0.80             0.86               5                   262   
2                0.11             0.88               7                   272   
3                0.72             0.87               5                   223   
4                0.37             0.52               2                   159   

   time_spend_company  Work_accident  left  promotion_last_5years Department  \
0                   3              0     1                      0      sales   
1                   6              0     1                      0      sales   
2                   4              0     1                      0      sales   
3                   5              0     1                      0      sales   
4                   3              0     1                      0      sales   

   salary  
0     low  
1  medium  
2  medium  
3     low  
4     low

In [ ]:
np.unique(df["Department"])

array(['IT', 'RandD', 'accounting', 'hr', 'management', 'marketing',
       'product_mng', 'sales', 'support', 'technical'], dtype=object)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14999 entries, 0 to 14998
Data columns (total 10 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   satisfaction_level     14999 non-null  float64
 1   last_evaluation        14999 non-null  float64
 2   number_project         14999 non-null  int64  
 3   average_montly_hours   14999 non-null  int64  
 4   time_spend_company     14999 non-null  int64  
 5   Work_accident          14999 non-null  int64  
 6   left                   14999 non-null  int64  
 7   promotion_last_5years  14999 non-null  int64  
 8   Department             14999 non-null  object 
 9   salary                 14999 non-null  object 
dtypes: float64(2), int64(6), object(2)
memory usage: 1.1+ MB


In [ ]:
df.describe()

satisfaction_level  last_evaluation  number_project  \
count        14999.000000     14999.000000    14999.000000   
mean             0.612834         0.716102        3.803054   
std              0.248631         0.171169        1.232592   
min              0.090000         0.360000        2.000000   
25%              0.440000         0.560000        3.000000   
50%              0.640000         0.720000        4.000000   
75%              0.820000         0.870000        5.000000   
max              1.000000         1.000000        7.000000   

       average_montly_hours  time_spend_company  Work_accident          left  \
count          14999.000000        14999.000000   14999.000000  14999.000000   
mean             201.050337            3.498233       0.144610      0.238083   
std               49.943099            1.460136       0.351719      0.425924   
min               96.000000            2.000000       0.000000      0.000000   
25%              156.000000            3.000000       0.000000      0.000000   
50%              200.000000            3.000000       0.000000      0.000000   
75%              245.000000            4.000000       0.000000      0.000000   
max              310.000000           10.000000       1.000000      1.000000   

       promotion_last_5years  
count           14999.000000  
mean                0.021268  
std                 0.144281  
min                 0.000000  
25%                 0.000000  
50%                 0.000000  
75%                 0.000000  
max                 1.000000

In [ ]:
df.isnull().sum()

satisfaction_level       0
last_evaluation          0
number_project           0
average_montly_hours     0
time_spend_company       0
Work_accident            0
left                     0
promotion_last_5years    0
Department               0
salary                   0
dtype: int64

In [ ]:
variables = ["Department","salary"]

In [ ]:
df = pd.get_dummies(df, columns=variables, drop_first=True)

In [ ]:
X_train = df.drop("left",axis =1)
y_train = df["left"]
X_train

satisfaction_level  last_evaluation  number_project  \
0                    0.38             0.53               2   
1                    0.80             0.86               5   
2                    0.11             0.88               7   
3                    0.72             0.87               5   
4                    0.37             0.52               2   
...                   ...              ...             ...   
14994                0.40             0.57               2   
14995                0.37             0.48               2   
14996                0.37             0.53               2   
14997                0.11             0.96               6   
14998                0.37             0.52               2   

       average_montly_hours  time_spend_company  Work_accident  \
0                       157                   3              0   
1                       262                   6              0   
2                       272                   4              0   
3                       223                   5              0   
4                       159                   3              0   
...                     ...                 ...            ...   
14994                   151                   3              0   
14995                   160                   3              0   
14996                   143                   3              0   
14997                   280                   4              0   
14998                   158                   3              0   

       promotion_last_5years  Department_RandD  Department_accounting  \
0                          0             False                  False   
1                          0             False                  False   
2                          0             False                  False   
3                          0             False                  False   
4                          0             False                  False   
...                      ...               ...                    ...   
14994                      0             False                  False   
14995                      0             False                  False   
14996                      0             False                  False   
14997                      0             False                  False   
14998                      0             False                  False   

       Department_hr  Department_management  Department_marketing  \
0              False                  False                 False   
1              False                  False                 False   
2              False                  False                 False   
3              False                  False                 False   
4              False                  False                 False   
...              ...                    ...                   ...   
14994          False                  False                 False   
14995          False                  False                 False   
14996          False                  False                 False   
14997          False                  False                 False   
14998          False                  False                 False   

       Department_product_mng  Department_sales  Department_support  \
0                       False              True               False   
1                       False              True               False   
2                       False              True               False   
3                       False              True               False   
4                       False              True               False   
...                       ...               ...                 ...   
14994                   False             False                True   
14995                   False             False                True   
14996                   False             False                True   
14997                   False             False      

In [ ]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)

In [ ]:
model = Sequential(
    [
        Dense(units = 21,activation = "relu"),
        Dense(units = 14,activation ="relu"),
        Dense(units = 7,activation = "relu"),
        Dense(units = 1,activation = "linear")
        ]
)

model.compile(
    optimizer = Adam(learning_rate = 0.01),
    loss = tf.keras.losses.MeanSquaredError()
)

In [ ]:
X_train , X_test ,y_train,y_test = train_test_split(X_train,y_train,train_size=0.7,random_state=55)

In [ ]:
model.fit(X_train,y_train,epochs = 25)

Epoch 1/25
329/329 [==============================] - 2s 2ms/step - loss: 0.0760
Epoch 2/25
329/329 [==============================] - 1s 2ms/step - loss: 0.0406
Epoch 3/25
329/329 [==============================] - 1s 2ms/step - loss: 0.0377
Epoch 4/25
329/329 [==============================] - 1s 2ms/step - loss: 0.0352
Epoch 5/25
329/329 [==============================] - 1s 3ms/step - loss: 0.0352
Epoch 6/25
329/329 [==============================] - 1s 4ms/step - loss: 0.0336
Epoch 7/25
329/329 [==============================] - 1s 3ms/step - loss: 0.0335
Epoch 8/25
329/329 [==============================] - 1s 3ms/step - loss: 0.0323
Epoch 9/25
329/329 [==============================] - 1s 4ms/step - loss: 0.0317
Epoch 10/25
329/329 [==============================] - 1s 2ms/step - loss: 0.0309
Epoch 11/25
329/329 [==============================] - 1s 2ms/step - loss: 0.0307
Epoch 12/25
329/329 [==============================] - 1s 2ms/step - loss: 0.0303
Epoch 13/25
329/329 [====

In [ ]:

y_predicted =model.predict(X_test)

141/141 [==============================] - 0s 1ms/step


In [ ]:
from sklearn.metrics import accuracy_score
# accuracy_score(y_test.astype(float),y_predicted.astype(float))


In [ ]:
y_predicted


array([[0.01563505],
       [0.01563505],
       [0.01563505],
       ...,
       [1.0442741 ],
       [0.8255294 ],
       [0.01563505]], dtype=float32)

In [ ]:
y_predicted.shape

(4500, 1)

In [ ]:
y_test.shape

(4500,)

In [ ]:
y_predicted = np.array(y_predicted).astype(float)
y_test = np.array(y_test).astype(float)

y_predicted = np.round(y_predicted)
y_predicted

array([[0.],
       [0.],
       [0.],
       ...,
       [1.],
       [1.],
       [0.]])

In [ ]:
y_test.reshape(-1,1)
y_predicted.reshape(-1,1)
counter = 0
for i in range(len(y_predicted)):
  if y_predicted[i] == y_test[i]:
    counter +=1
print(counter/len(y_predicted))

0.968


In [ ]:
np.unique(y_predicted)

array([0., 1.])

In [ ]:
y_predicted_train = model.predict(X_train)
y_predicted_train = np.array(y_predicted_train)
y_predicted_train = np.round(y_predicted_train)
counter = 0
y_train = np.array(y_train)
for i in range(len(y_train)):
  if y_train[i] == y_predicted_train[i]:
    counter +=1
print(counter/len(y_train))

# By far my best model having an accuracy of approcimately 98% on the training set and 97% on the test set


329/329 [==============================] - 1s 2ms/step
0.9739022764072769
