In [ ]:
import numpy as np
import matplotlib.pyplot as plt
# plt.style.use('./deeplearning.mplstyle')
import tensorflow as tf
# from tensorflow.keras.models import Sequential
# from tensorflow.keras.layers import Dense
from IPython.display import display, Markdown, Latex
from sklearn.datasets import make_blobs
# %matplotlib widget
# from matplotlib.widgets import Slider
# from lab_utils_common import dlc
# from lab_utils_softmax import plt_softmax
import logging
logging.getLogger("tensorflow").setLevel(logging.ERROR)
tf.autograph.set_verbosity(0)

In [ ]:
def my_softmax(z):
    ez = np.exp(z)              #element-wise exponenial
    sm = ez/np.sum(ez)
    return(sm)

In [ ]:
# make  dataset for example
centers = [[-5, 2], [-2, -2], [1, 2], [5, -2]]
X_train, y_train = make_blobs(n_samples=2000, centers=centers, cluster_std=1.0,random_state=30)

In [ ]:
print(X_train)

[[ 1.55508243  0.84801682]
 [-5.33749882  1.03397255]
 [-4.09353183  0.67843096]
 ...
 [-0.84437575 -1.94991543]
 [ 5.0377068  -2.92221685]
 [ 0.38198674  1.49735733]]


In [ ]:
print(y_train)

[2 0 0 ... 1 3 2]


In [ ]:
model = tf.keras.Sequential(
    [

        tf.keras.layers.Dense(units=25,activation="relu"),
    tf.keras.layers.Dense(units=15,activation="relu"),
    tf.keras.layers.Dense(units=4,activation="softmax")
    ]
)

In [ ]:
model.compile(
    loss = tf.keras.losses.SparseCategoricalCrossentropy(),
    optimizer = tf.keras.optimizers.Adam(0.01),
)

model.fit(X_train,y_train,epochs = 100)

Epoch 1/100
63/63 [==============================] - 1s 2ms/step - loss: 0.1729
Epoch 2/100
63/63 [==============================] - 0s 2ms/step - loss: 0.0377
Epoch 3/100
63/63 [==============================] - 0s 2ms/step - loss: 0.0278
Epoch 4/100
63/63 [==============================] - 0s 2ms/step - loss: 0.0211
Epoch 5/100
63/63 [==============================] - 0s 2ms/step - loss: 0.0205
Epoch 6/100
63/63 [==============================] - 0s 2ms/step - loss: 0.0228
Epoch 7/100
63/63 [==============================] - 0s 2ms/step - loss: 0.0163
Epoch 8/100
63/63 [==============================] - 0s 2ms/step - loss: 0.0173
Epoch 9/100
63/63 [==============================] - 0s 2ms/step - loss: 0.0195
Epoch 10/100
63/63 [==============================] - 0s 2ms/step - loss: 0.0201
Epoch 11/100
63/63 [==============================] - 0s 2ms/step - loss: 0.0179
Epoch 12/100
63/63 [==============================] - 0s 2ms/step - loss: 0.0156
Epoch 13/100
63/63 [=================

In [ ]:
p_nonpreferred = model.predict(X_train)
print(p_nonpreferred [:2])
print("largest value", np.max(p_nonpreferred), "smallest value", np.min(p_nonpreferred))

63/63 [==============================] - 0s 1ms/step
[[2.6745795e-06 7.7534512e-09 9.9999720e-01 8.0958742e-09]
 [9.9999994e-01 2.5496244e-10 1.1290312e-09 1.7647940e-17]]
largest value 0.99999994 smallest value 0.0


In [ ]:
preferred_model = tf.keras.Sequential(
    [
        tf.keras.layers.Dense(25, activation = 'relu'),
        tf.keras.layers.Dense(15, activation = 'relu'),
        tf.keras.layers.Dense(4, activation = 'linear')   #<-- Note
    ]
)
preferred_model.compile(
    loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),  #<-- Note
    optimizer=tf.keras.optimizers.Adam(0.001),
)

preferred_model.fit(
    X_train,y_train,
    epochs=10)

Epoch 1/10
63/63 [==============================] - 1s 2ms/step - loss: 1.3737
Epoch 2/10
63/63 [==============================] - 0s 2ms/step - loss: 0.5357
Epoch 3/10
63/63 [==============================] - 0s 2ms/step - loss: 0.2626
Epoch 4/10
63/63 [==============================] - 0s 1ms/step - loss: 0.1544
Epoch 5/10
63/63 [==============================] - 0s 2ms/step - loss: 0.1074
Epoch 6/10
63/63 [==============================] - 0s 2ms/step - loss: 0.0842
Epoch 7/10
63/63 [==============================] - 0s 2ms/step - loss: 0.0706
Epoch 8/10
63/63 [==============================] - 0s 2ms/step - loss: 0.0623
Epoch 9/10
63/63 [==============================] - 0s 2ms/step - loss: 0.0563
Epoch 10/10
63/63 [==============================] - 0s 1ms/step - loss: 0.0514


In [ ]:
p_preferred = preferred_model.predict(X_train)
print(f"two example output vectors:\n {p_preferred[:2]}")
print("largest value", np.max(p_preferred), "smallest value", np.min(p_preferred))

63/63 [==============================] - 0s 1ms/step
two example output vectors:
 [[-0.5855501  -1.1746771   4.599722    1.4259931 ]
 [ 6.922118    2.396075   -0.99896437 -5.9413185 ]]
largest value 14.404421 smallest value -9.154756


In [ ]:
sm_preferred = tf.nn.softmax(p_preferred).numpy()
print(f"two example output vectors:\n {sm_preferred[:2]}")
print("largest value", np.max(sm_preferred), "smallest value", np.min(sm_preferred))

two example output vectors:
 [[5.3290213e-03 2.9566034e-03 9.5188081e-01 3.9833605e-02]
 [9.8893481e-01 1.0703657e-02 3.5899240e-04 2.5624070e-06]]
largest value 0.9999886 smallest value 4.7269794e-10


In [ ]:
for i in range(5):
    print( f"{p_preferred[i]}, category: {np.argmax(p_preferred[i])}")

[-0.5855501 -1.1746771  4.599722   1.4259931], category: 2
[ 6.922118    2.396075   -0.99896437 -5.9413185 ], category: 0
[ 5.1077538  2.233546  -0.8733397 -4.719685 ], category: 0
[-0.83863556  3.9463406  -1.997936   -1.1608766 ], category: 1
[ 2.4017465 -1.7322303  6.843753  -1.0289676], category: 2
